name: This That We Have Now
favicon: null
layout_spectrum: 0.26784
typography_spectrum: 0.94289
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e2c00'
    - '#f0d4be'
    - '#4d4d59'
    - '#a5978e'
    - '#7f4e01'
  brandStrength: 0.3091358330566436
  lightness: 0.798452774528414
  saturation: 0.07823226926848292
  rhythmicContrast: 0.739231126382947
purpose: []
