name: This That We Have Now
favicon: null
layout_spectrum: 0.6145284175872803
typography_spectrum: 0.8144934680312872
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3091358330566436
  lightness: 0.798452774528414
  saturation: 0.07823226926848292
  rhythmicContrast: 0.739231126382947
purpose: []
